### ISSUE TITLE
[BUG] Non-ascii characters problem

### ISSUE THREAD

**Issue by yuchen-lea** [xthursdayx/docker-gpodder#14]
## Current Behavior

Non-ascii characters don't display correctly.

<img width="1700" alt="image" src="https://user-images.githubusercontent.com/7555085/134605987-15ac8961-d13e-4273-9d75-c944182fa578.png">

This should be Chinese character.

## Steps to Reproduce

Non-ascii characters display without problem in gPodder desktop client, but become Mojibake in docker.

I'm not sure where the problem lies, I tried to change the locale but it didn't work:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7555085/134606601-139ec6b3-ee2f-4a24-b775-27559ac31ac8.png">

## Environment

QNAP TS-453B

**OS:** QNAP
**CPU architecture:** Intel Celeron N3150

## Command used to create docker container (run/create/compose/screenshot)

I tried both:

> docker create --name=gPodder-cn --restart=always \
>   -p 8066:8080 \
>   -p 3389:3389 \
>   -e LANG="zh_CN.utf8" \
>   -e LANGUAGE="zh_CN.utf8" \
>   -v /share/App/gpodder:/config \
>   -v /share/yuchen/Podcasts:/downloads \
>   -e PUID=0 -e PGID=0 xthursdayx/gpodder-docker

and

> docker create --name=gPodder --restart=always \
>   -p 8066:8080 \
>   -p 3389:3389 \
>   -v /share/App/gpodder:/config \
>   -v /share/yuchen/Podcasts:/downloads \
>   -e PUID=0 -e PGID=0 xthursdayx/gpodder-docker

**Comment by xthursdayx** [comment]
Thanks for the error info. I'm in the midst of redesigning this docker imager, so I'll take this issue into account when I release the next version. I'll report back here when I push the next version.

**Comment by yuchen-lea** [comment]
Glad to hear this!

You can use this for test: https://lushu88.com/rss

**Comment by xthursdayx** [comment]
Sorry that it's taken me a while to get back to this. However, I've now rebased this docker image and fixed the problem you were having. Please pull the latest version and see if it fixes your issue. 

If you have existing settings and/or subscriptions in gPodder that you want to preserve, please copy the contents of `/config/gPodder` to `/config`. Let me know if you have any problems. Cheers!
