### ISSUE TITLE
Question about the base image change

### ISSUE THREAD

**Issue by tanja84dk** [xthursdayx/docker-gpodder#16]
I have a question is RDP still accessible on the new base image you have changed to?

**Comment by xthursdayx** [comment]
Sorry about that, I didn't think anyone really used the RDP port for this image. I'm actually not sure if RDP access will work or not. The base image I used is primarily for WebUI connections, but I added some code and exposed port 3389 to a new RDP branch of this repo and just pushed the RDP tagged image to Docker Hub. 

If you have the time and don't mind experimenting try pulling `xthursdayx/gpodder-docker:RDP` and see if you're able to connect to the container via RDP.

**Comment by tanja84dk** [comment]
No worries I just wanted to make sure before upgrading my containers.
Because the web RDP at least used before did never work properly on smaller devices like phones or small tablets, but that is not your fault

Which is why I always used directly RDP to get around the issues and get the full application directly on my phone or tablet.


I'll give it a test when I get home but it's okay if you don't feel like supporting RDP anymore because the container I'm on still ( many month old ) have not had any issues so I would be okay just not upgrading

**Comment by tanja84dk** [comment]
After a test with the same hashes and account that I always use for gPodder containers i have to say it fails as soon as it has authenticated to the RDP server.

And I have on purpose reused the same password hash as my other container to make sure it were the same password

I did also try to set it up without password and it still hit the same error

Also if it's easier for you and so you don't have broken images on docker hub I don't mind then if I have to run the docker build myself when testing ( on a git pull of the branch ) because I'm used to that when I build my own personal images

![image](https://user-images.githubusercontent.com/1285458/142225988-53b68cb3-807c-433f-9571-516c566c439c.png)
