### ISSUE TITLE
[REQUEST] Update of gpodder

### ISSUE THREAD

**Issue by tanja84dk** [xthursdayx/docker-gpodder#26]
Would it be possible to get gpodder updated to at least version 3.11.0 because of some sites there is fixed in the newer versions
like Speakr/Global Audio Hosting is at least one of those there has issues on 3.10.21
The version I see in the image from a git status is 3.10.21

I did try myself to pull and checkout at least gpodder version 3.11.0 within a container of the newest gpodder-docker with success and had a few issues when I tried 3.11.1 first but I dont know if it actually were because of the database upgrade there is from 3.11.0 and it were first time upgrading.

I do also gave to add that I removed youtube-dl and added the yt-dlp binary to my container also ( personal preffence but not sure if it did anything for me )

info about 3.11.0 from Jul 31, 2022 https://github.com/gpodder/gpodder/releases/tag/3.11.0
info about 3.11.1 from last week https://github.com/gpodder/gpodder/releases/tag/3.11.1

**Comment by xthursdayx** [comment]
Sorry for the delay with this update, the images are now updated to 3.11.1 and seems to be working (also including yt-dlp). If you see any issues please feel free to reopen this issue and let me know.
