### ISSUE TITLE
[Feature Request] arm64 (raspberrypi) docker support

### ISSUE THREAD

**Issue by peterpepo** [xthursdayx/docker-gpodder#36]
Hello, is it possible to build a raspberry pi3b - BCM2837 docker image?
```
pi@raspberrypi:~/docker/gpodder $ docker compose up -d
[+] Running 0/1
 ⠋ gpodder Pulling                                                                                              3.0s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by xthursdayx** [comment]
Currently looking into this now that I've rebased the container.

**Comment by xthursdayx** [comment]
I have now pushed a multi-arch image that includes support for arm64/v8. I've tested on an arm64 machine locally, but could you please pull the updated image and ensure that it is working on your Raspberry Pi?

**Comment by peterpepo** [comment]
Hello, @xthursdayx - thanks for your amazing work and making this image multiarch.
I've successfully pulled, started new image and backed up my favourite podcast :)

**Comment by xthursdayx** [comment]
Great, glad to hear it!
